# Generated by Django 3.1.3 on 2021-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=40)),
                ('Slug', models.SlugField(unique=True)),
                ('MainText', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(default='app/static/img/post/default_news.jpeg', null=True, upload_to='app/static/img/post')),
                ('Status', models.CharField(choices=[('d', 'Draft'), ('p', 'Publish')], default='p', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
