# Generated by Django 3.1.2 on 2021-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.TextField(),
        ),
    ]
