# Generated by Django 3.1.2 on 2021-01-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_auto_20210124_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Title',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=40),
        ),
    ]
